config/routes.rb
Rails.application.routes.draw do
 
 resources :passwords, controller: "clearance/passwords", only: [:create, :new]
 resource :session, controller: "clearance/sessions", only: [:create]
 resources :users, controller: "clearance/users", only: [:create] do
   resource :password,
     controller: "clearance/passwords",
     only: [:create, :edit, :update]
 end

 root 'welcome#index'

  get '/search', to: 'facilities#search', as: "search"
  get '/search_bookings', to: 'bookings#search_bookings', as: "search_bookings"

resources :users do
  resources :facilities 
end

resources :bookings, only: [:update]

 resources :facilities do
    resources :bookings, only: [:index, :new, :show, :create] do
      resources :payments, only: [:new, :create]
    end
  end

 resources :users, controller: "users", only: :show
 get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, only: [:show, :edit, :update] do 
    resources :teams, only: [:new, :create, :edit, :update, :show, :destroy] 
  end

  get "/teams/:team_id/user_teams/new" => 'user_teams#new'
  post "/teams/:team_id/user_teams" => 'user_teams#create', as: "add_team_members"
  delete "/team/:team_id/user_teams/:id", to: 'user_teams#destroy', as: "delete_team_member"

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :photos

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  has_many :payments
  belongs_to :facility
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :facility, presence: true

  searchkick match: :word_start, searchable: [:title, :notes, :facility_location_name]
end

app/controllers/booking_controller.rb
class BookingsController < ApplicationController
  before_action :require_login
  before_action :find_user, only: [:show, :edit, :update, :destroy]
 

  def index
  end

  def show
  end

  def new
  end

  def create
    @booking = current_user.bookings.create(booking_params)

    if @booking.save
      redirect_to @booking
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if current_user.bookings.update(booking_params)
      redirect_to @booking
    else
      render 'edit'
  end

  def destroy
    @booking.destroy
    redirect_to user_team_bookings_path
  end

  private 

  def find_user
    @user = User.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:date, :private, :title, :notes, :facility)
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :require_login
  
  before_action :find_facility, only: [:new, :create]

  def index
    @bookings = Booking.all
  end

  def search_bookings
        @bookings = Booking.search(params[:term], fields: ["title", "notes", "facility_location_name"], mispellings: {below: 5})
        if @bookings.blank?
          redirect_to root_path, flash:{danger: "no successful search result"}
        else
          render :index
        end
  end

  def update
    
    @booking = Booking.find(params[:id])
    @booking.participant_id << current_user.id
    @booking.save
    redirect_to facility_booking_path(@booking.facility.id, @booking.id), notice: "You've joined this booking."
  end
  
  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = @facility.bookings.new
  end


  def create
    
    a = start_date
    b = end_date
    @price = @facility.price_per_hour

    @booking = @facility.bookings.new(booking_params)
    @booking.start_date = a
    @booking.end_date = b
    @hours = (@booking.end_date - @booking.start_date)/3600

    @total = @hours * @price
    @booking.total = @total
    @booking.user_id = current_user.id
    @booking.facility_location_name = @facility.location_name

    if @booking.save 
      redirect_to facility_booking_path(@facility, @booking), notice: "Booking has been successfully created"
    else
      render 'new'
    end
  end

  private 

  def start_date
    start_date_string = params[:start_date]
    return start_date = datify(start_date_string).to_datetime
  end

  def end_date
    end_date_string = params[:end_date]
    return end_date = datify(end_date_string).to_datetime
  end

  def datify(date)
    mth = date[0..2]
    day = date[3..5]
    yr = date[6..9]
    day + mth + yr + date[10..17]
  end

  def booking_params
    params.require(:booking).permit(:private, :title, :notes)
  end

  def find_facility
    @facility = Facility.find(params[:facility_id])
  end

  #  def find_facility_for_new
  #   byebug
  #   @facility = Facility.find(params[:facility_id])
  # end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <strong>Make A Booking</strong>
  </div>

  <div class="panel-body">
    <div class="container">
      
     <%= form_for(@booking, :url=> { :action => "create"}) do |form| %>

        <div class="container">
            <div class='col-md-5'>
                <div class="form-group">
                 <%= label_tag :start_date, 'Start Date & Time' %>
                    <div class='input-group date' id='datetimepicker6'>
                    <%= text_field_tag :start_date, nil, class: 'form-control', data: { date_format: 'YYYY/MM/DD' } %>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </div>

            <div class='col-md-5'>
                <div class="form-group">
                <%= label_tag :end_date, 'End Date & Time' %>
                    <div class='input-group date' id='datetimepicker7'>
                    <%= text_field_tag :end_date, nil, class: 'form-control', data: { date_format: 'YYYY/MM/DD' } %>
                      <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <%= form.label :title, 'Title' %>
            <%= form.text_field :title, placeholder: 'Title' %>
          </div>
        </div><br>

        <div class="row">
          <div class="col-md-6">
            <%= form.label :notes, 'Notes' %>
            <%= form.text_area :notes, placeholder: 'Notes' %>
          </div>
        </div><br>

        <div class="row">
          <div class="col-md-6">
            <%= form.label :private, 'Tick for Private Event' %>
            <%= form.check_box :private %>
          </div>
        </div><br>

        <div class="row">
         <div class="col-md-6">
          <%= form.submit "Book" %>
         </div>
        </div>

      <% end %>
    </div>
  </div>
</div>





<script type="text/javascript">
    $(function () {
        $('#datetimepicker6').datetimepicker();
        $('#datetimepicker7').datetimepicker({
            useCurrent: true //Important! See issue #1075
        });
        $("#datetimepicker6").on("dp.change", function (e) {
            $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
        });
        $("#datetimepicker7").on("dp.change", function (e) {
            $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
        });
    });
</script>

app/views/bookings/index.html.erb
<div class="col-md-9" style="margin-left:200px; margin-top:50px;">
    <div class="panel panel-default">
        <div class="panel-heading"> Bookings </div>
            <div class="panel-body">
            <% @bookings.each do |booking| %>
                <div class="row">
                    <div class="col-md-9 col-md-offset-1">
                        <h1><strong>Location Name: <%= booking.title %></strong></h1>
                    </div>
                <div class="row">    
                    <div class="col-md-9 col-md-offset-1">
                        <h4><strong>Notes: <%= booking.notes %></strong></h4>
                    </div>
                </div>

                <div class="row">    
                    <div class="col-md-9 col-md-offset-1">
                        <h4>Start Date: <%= booking.start_date.strftime('%v') %></h4>
                    </div>

                    <div class="col-md-9 col-md-offset-1">
                        <h4>End Date: <%= booking.end_date.strftime('%v') %></h4>
                    </div>

                    <%= link_to "View", facility_booking_path(booking.facility.id, booking.id), class: "btn btn-primary" %>
                    <%= link_to "Join Booking", booking_path(booking), method: :put, class: "btn btn-danger" %>

                </div>
            <% end %>    
                </div>
            </div>
        </div>
    </div>

app/views/bookings/new.html.erb
<div class="col-md-9" style="margin-left:50px; margin-top:50px;">
<div class="container">
	<div class="row">
		<%= render 'form' %>
	</div>
</div>
</div>

app/views/bookings/show.html.erb
<div class="col-md-9" style="margin-left:200px; margin-top:50px;">
	<div class="panel panel-default">
		<div class="panel-heading"><strong> Your Bookings </strong></div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-9 col-md-offset-1">
						<h1><strong>Title: <%= @booking.title %></strong></h1>
					</div>
				<div class="row">	
					<div class="col-md-9 col-md-offset-1">
						<h4><strong>Notes: <%= @booking.notes %></strong></h4>
					</div>
				</div>

				<div class="row">	
					<div class="col-md-9 col-md-offset-1">
						<h4>Start Time:<%= @booking.start_date.strftime('%v') %></h4>
					</div>

					<div class="col-md-9 col-md-offset-1">
						<h4>End Time:<%= @booking.end_date.strftime('%v') %></h4>
					</div>

				</div>

					<div class="col-md-9 col-md-offset-1">
						<h4>Total: $<%= @booking.total %></h4>
					</div>	
				</div>
						<hr>
					<strong>Payment Status:</strong>
      		<% if @booking.payments.where(status: :authorized).count == 0 %>
      			<span class="btn btn-danger"> NOT PAID </span>
       			<%= link_to 'Pay Now' , new_facility_booking_payment_path(@booking.facility, @booking) + "?id=" + @booking.id.to_s, class: "btn btn-primary"  %>
      		<% else %>
      			<span class="btn btn-success">PAID</span>
      		<% end %>

			</div>
		</div>
	</div>