config/routes.rb
Rails.application.routes.draw do
 
 resources :passwords, controller: "clearance/passwords", only: [:create, :new]
 resource :session, controller: "clearance/sessions", only: [:create]
 resources :users, controller: "clearance/users", only: [:create] do
   resource :password,
     controller: "clearance/passwords",
     only: [:create, :edit, :update]
 end

 root 'welcome#index'

  get '/search', to: 'facilities#search', as: "search"
  get '/search_bookings', to: 'bookings#search_bookings', as: "search_bookings"

resources :users do
  resources :facilities 
end

resources :bookings, only: [:update]

 resources :facilities do
    resources :bookings, only: [:index, :new, :show, :create] do
      resources :payments, only: [:new, :create]
    end
  end

 resources :users, controller: "users", only: :show
 get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, only: [:show, :edit, :update] do 
    resources :teams, only: [:new, :create, :edit, :update, :show, :destroy] 
  end

  get "/teams/:team_id/user_teams/new" => 'user_teams#new'
  post "/teams/:team_id/user_teams" => 'user_teams#create', as: "add_team_members"
  delete "/team/:team_id/user_teams/:id", to: 'user_teams#destroy', as: "delete_team_member"

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :photos

end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploaders :avatars, AvatarUploader
  include Clearance::User

  validates :email, uniqueness: true
  has_many :authentications, :dependent => :destroy
  has_many :facilities
  has_many :bookings
  has_many :user_teams
  has_many :teams

  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      #u.first_name = auth_hash["info"]["first_name"]
      # u.last_name = auth_hash["info"]["last_name"]
      # u.friendly_name = auth_hash["info"]["name"]
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.password = SecureRandom.hex(6)
      u.authentications<<(authentication)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end


  # def password_optional?
  #   true
  # end

end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def new
    @user = user_from_params
    render template: "users/new"
  end

  def create
    @user = user_from_params
    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
    end
  end

  def user_params
    params[Clearance.configuration.user_parameter] || Hash.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update]

  def update
  	if @user.update_attributes(user_params)
  		redirect_to user_path
  	else
  		render :edit
  	end
  end

  private
	def user_params	
		params.require(:user).permit(:email, :password, :name, :gender, :description, :contact_detail, :location_description, {avatars:[]})
	end

  def set_user
  	@user = User.find(params[:id])
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<div class="submit-field">
  <%= form.submit %>
</div>

app/views/users/edit.html.erb
<div id="clearance" class="sign-up">
 <h2><%= t(".update_user") %></h2>

    <%= form_for(@user) do |form| %>
        <div class="text-field">
          <%= form.label :name %>
          <%= form.text_field :name %>
        </div>

        <div class="form-group">
            <label>Gender</label>
          <%= form.select :gender, [["Male", "Male"], ["Female", "Female"]], prompt: "Please select", class: "form-control" %>
        </div>

        <div class="form-group">
            <label>Description</label>
            <%= form.text_area :description, rows: 5, placeholder: "Tell us more about yourself eg. sport.", class: "form-control" %>
        </div>

        <div class="text-field">
          <%= form.label :contact_detail %>
          <%= form.text_field :contact_detail %>
        </div>

        <div class="form-group">
          <label>City</label>
            <%= form.select :location_description, [["Petaling Jaya","Petaling Jaya"], ["KL","KL"], ["Klang","Klang"]],prompt: "Please select", class: "form-control" %>
      </div>    

        <div class="btn btn-default btn-file">
            <%= form.file_field :avatars, multiple: true %>
        </div>
        
        <div class="submit-field">
          <%= form.submit "Submit", class: "btn btn-primary"  %>
        </div>
        
    <% end %>

</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
    
  <% end %>

	
     <style>
        body {
          background-image: url('http://www.tmwallpaper.com/mod/creative/1600x900/wide-wallpaper-1600x900-063.jpg');
        }

      </style>

</div>

app/views/users/show.html.erb
<div class="user-container" style="margin-top:100px; margin-left:120px;">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><h2 class="img-circle">
                      <% if current_user.name.nil? %>

                        <h3>Whats your name btw? Please update us more basic details of yours. Go to <%= link_to "update profile", edit_user_path(current_user.id) %>.<br></h3>

                        <h4><%= "Your email address is: " + current_user.email %><br></h4>

                      <% else %>
                        <%= current_user.name %>
                      <% end %>

                      <%= image_tag (current_user.avatars[0].thumb.url) if current_user.avatars[0] != nil %></h2></h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class=" col-md-9 col-lg-9 ">
                            <table class="table table-user-information">
                                <tbody>
           

                                    <tr>
                                     
       
                                       <% if current_user.name.nil? %>

                                         <h3>Whats your name btw? Please update us more basic details of yours. Go to <%= link_to "update profile", edit_user_path(current_user.id) %>.<br></h3>
                                         <h4><%= "Your email address is: " + current_user.email %><br></h4>
                                       
                                       <% else %>
                                         <%= "Hi, " + current_user.name + "! We appreciate every moment you have with us =)" %><br>

                                         
                                         <% if current_user.teams.nil? %>
                                          <div id="create-team-button">
                                           <%= button_to "let's create a team!", new_user_team_path(current_user.id) %><br>
                                          </div>

                                         <% else %>

                                           <% teams = Team.where(user_id: current_user.id)
                                           user_teams = UserTeam.where(user_id: current_user.id) %>

                                           <% if teams.count != 0 %>
                                             <%= "Teams where you are an admin:" %><br>
                                             <% teams.each_with_index do |t, index| %>
                                               <%= "#{index+1}.. #{t.name}"%>
                                               <%= link_to "view", user_team_path(current_user, t) %><br>
                                             <% end %>
                                           <% end %>

                                           <% if user_teams.count != 0 %>
                                             <%= "Teams you are a member:" %><br>
                                             <% user_teams.each_with_index do |ut, index|%>
                                               <%= "#{index+1}.. #{ut.team.name}" %>
                                               <%= link_to "view", user_team_path(current_user, ut.team) %><br>
                                             <% end %>

                                           <% end %>

                                           <%= link_to "let's create more kick-ass teamsss!", new_user_team_path(current_user.id) %><br>

                                         <% end %>
                                        <br><br>
                                         <%= "Below is your public information:" %><br>
                                         <%= "Name: #{current_user.name}" if current_user.name != nil %><br>
                                         <%= "Gender: #{current_user.gender}" if current_user.gender != nil %><br>
                                         <%= "Profile Description: #{current_user.description}" if current_user.description != nil%><br>
                                         <%= "Contact: #{current_user.contact_detail}" if current_user.contact_detail != nil %><br>
                                         <%= "Location: #{current_user.location_description}" if current_user.location_description != nil %><br>
                                         <%= link_to "update profile", edit_user_path(current_user.id) %><br>
                                       

                                       
                                         <% bookings = current_user.bookings %>
                                         <% facilities = current_user.facilities %>
                                        <br><br>
                                         <% if bookings.count != 0 %>
                                           <%= "You have #{bookings.count} bookings booked through our sites." %><br>
                                           <% bookings.each_with_index do |b, index| %>
                                             <%= "#{index+1}.. #{b.title}" %>
                                             <%= link_to "View", facility_booking_path(b.facility.id, b.id), class: "btn btn-primary" %><br>
                                           <% end %>
                                         <% end %>
                                        <br><br>
                                         <% if facilities.count != 0 %>
                                           <%= "You have #{facilities.count} facitilites listed on our sites." %><br>
                                           <% facilities.each_with_index do |f, index| %>
                                             <%= "#{index+1}.. #{f.location_name}" %>
                                             <%= link_to "View", user_facility_path(current_user.id, f.id), class: "btn btn-primary" %><br>
                                           <% end %>
                                         <% end %>
                                        <% end %>
                                        </div>
                                      </div>



                                    </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- template -->

<div id="clearance" class="sign-up">
  <style>
  body {
     background-image: url('http://www.tmwallpaper.com/mod/creative/1600x900/wide-wallpaper-1600x900-063.jpg');
  }

  </style>