config/routes.rb
Rails.application.routes.draw do
 
 resources :passwords, controller: "clearance/passwords", only: [:create, :new]
 resource :session, controller: "clearance/sessions", only: [:create]
 resources :users, controller: "clearance/users", only: [:create] do
   resource :password,
     controller: "clearance/passwords",
     only: [:create, :edit, :update]
 end

 root 'welcome#index'

  get '/search', to: 'facilities#search', as: "search"
  get '/search_bookings', to: 'bookings#search_bookings', as: "search_bookings"

resources :users do
  resources :facilities 
end

resources :bookings, only: [:update]

 resources :facilities do
    resources :bookings, only: [:index, :new, :show, :create] do
      resources :payments, only: [:new, :create]
    end
  end

 resources :users, controller: "users", only: :show
 get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, only: [:show, :edit, :update] do 
    resources :teams, only: [:new, :create, :edit, :update, :show, :destroy] 
  end

  get "/teams/:team_id/user_teams/new" => 'user_teams#new'
  post "/teams/:team_id/user_teams" => 'user_teams#create', as: "add_team_members"
  delete "/team/:team_id/user_teams/:id", to: 'user_teams#destroy', as: "delete_team_member"

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :photos

end

app/models/facility.rb
class Facility < ActiveRecord::Base
	has_many :bookings
	validates :user_id, presence: true
	belongs_to :user

	# geocoded_by :address
	# after_validation :geocode, if: :address_changed?

	# validates :start_date, presence: true
	# validates :end_date, presence: true
	# validates :private, presence: true
	# validates :title, presence: true
	# validates :notes, presence: true
	# validates :total, presence: true
	validates :sport, presence: true
	mount_uploaders :avatars, AvatarUploader
	searchkick match: :word_start, searchable: [:street, :city, :state, :start_time, :end_time, :description, :location_name, :ratings, :price_per_hour, :sport]
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: [:show, :edit, :update, :destroy]
  
  def index
    @facilities = Facility.all
  end

  def search
    @facilities = Facility.search(params[:term], fields: [:street, :city, :state, :start_time, :end_time, :description, :location_name, :ratings, :price_per_hour, :sport], mispellings: {below: 3})
    if @facilities.blank?
      redirect_to user_facilities_path, flash:{danger: "no successful search result"}
    else
      render :index
    end
  end

  def show

  end

  def new
    @facility = current_user.facilities.build
  end

  def create
    @facility = current_user.facilities.new(facility_params)

    if @facility.save
      redirect_to user_facility_path(current_user.id, @facility.id), notice: "Facility is successfully created"
    else
      render :new
    end
  end

  def edit
    if current_user.id == @facility.user.id
      @avatars = @facility.avatars
    else
      redirect_to root_path, notice: "You don't have access permission."
    end
  end

  def update
   
    if @facility.update(facility_params)
      redirect_to user_facility_path(current_user.id, @facility.id), notice: "Facility is successfully updated."
    else
      render :edit
    end
  end

  def destroy

    if @facility.destroy
      redirect_to user_facilities_path(current_user.id), notice: "Facility is deleted."
    else
      render :edit
    end
  end

  private

    def set_facility
      @facility = Facility.find(params[:id])
    end

    def facility_params
      params.require(:facility).permit(:street, :city, :state, :sport, :start_time, :end_time, :description, :location_name, :ratings, :price_per_hour, {avatars: []})
    end
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_form.html.erb
<div class="panel panel-default">
   <div class="panel-heading">
       Create your facility here
   </div>
   <div class="panel-body">
       <div class="container">
           
           
               <div class="row">
                   <div class="col-md-4 select">
                       <div class="form-group">
                                       <label>Facility Type</label>
                                       <%= form.select :sport, [["Futsal","Futsal"], ["Badminton","Badminton"], ["Basketball","Basketball"]], id: "sport", prompt: "Please select", class: "form-control" %>
                       </div>
                   </div>

                   <div class="col-md-4 select">
                       <div class="form-group">
                                       <label>City</label>
                                       <%= form.select :city, [["Petaling Jaya","Petaling Jaya"], ["KL","KL"], ["Klang","Klang"]], prompt: "Please select", class: "form-control" %>
                       </div>
                   </div>

                   <div class="col-md-4 select">
                       <div class="form-group">
                                       <label>Number of Hours</label>
                                       <%= form.select :price_per_hour, [["1",1], ["2",2], ["3",3], ["4",4], ["5",5], ["6+",6]], prompt: "Select...", class: "form-control" %>
                       </div>
                   </div>
               </div>

               <div class="row">
                   <div class="col-md-4 select">
                       <div class="form-group">
                                   <label>Ratings</label>
                                   <%= form.select :ratings, [["1",1], ["2",2], ["3",3], ["4+",4]], prompt: "Please select", class: "form-control" %>
                       </div>
                   </div><br><br>

               
                   <div class="form-group">
                               <label>Location Name</label>
                               <%= form.text_field :location_name, placeholder: "Name of your facility", class: "form-control" %>
                   </div>
               

               
                   <div class="form-group">
                               <label>Description</label>
                               <%= form.text_area :description, rows: 5, placeholder: "Tell us about your facility", class: "form-control" %>
                   </div>
               

               
                   <div class="form-group">
                               <label>Street</label>
                               <%= form.text_field :street, placeholder: "What is your street address?", class: "form-control" %>
                   </div>
               </div>
               
<div class="row">
                   <div class="col-md-4">
                       <div class="form-group">
                           <label>Price per hour</label>
                           <div class="input-group">
                               <div class="input-group-addon">$</div>
                               <%= form.text_field :price_per_hour, placeholder: "eg. $100", class: "form-control" %>
                           </div>    
                       </div>
                   </div>
               </div>

               <div class="row">
                   <div class="col-md-4">
                       <div class="form-group">                            
                           <span class="btn btn-default btn-file">
                               <i class="fa fa-cloud-upload fa-lg"></i> Upload Photos 
                               <%= form.file_field :avatars, multiple: true %>
                           </span>
                       </div>        
                   </div>
               </div>

               <div id="photos"><%= render 'photos/list' %></div>


               <div class="actions">
                   <%= form.submit "Save", class: "btn btn-primary" %>
               </div>
           
       </div>
   </div>
</div>

app/views/facilities/edit.html.erb
<%= form_for(@facility, url: "/users/#{current_user.id}/facilities/#{@facility.id}", html: {method: "patch"}) do |form| %>

		<%= render partial: '/facilities/form', object: form %>

<% end %>

app/views/facilities/index.html.erb
<div class="row">
    <div class="col-md-9" style="margin-left:200px; margin-top:50px;">
        <div class="panel panel-default">
            <div class="panel-heading">
                Facilities Listings
            </div>
            <div class="panel-body">
                
                <% @facilities.each do |facility| %>
                    <div class="row">
                        <div class="col-md-2">
                            
                        </div>        
                        <div class="col-md-7">
                            <h4><%= facility.location_name %></h4>
                            <%= image_tag (facility.avatars[0].thumb.url) if facility.avatars[0] != nil %>
                        </div>        
                        <div class="col-md-3 right">
                    
                            <%= link_to "View", user_facility_path(current_user.id, facility.id), class: "btn btn-primary" %>

                            <%= link_to "Book", new_facility_booking_path(facility.id), class: "btn btn-primary" %>

                        </div>        
                    </div>
                    <hr>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/facilities/new.html.erb
<%= form_for(@facility, url: "/users/#{current_user.id}/facilities", html: {method: "post"}) do |form| %>

<%= render partial: '/facilities/form', object: form %>

<% end %>

app/views/facilities/show.html.erb
<div class="panel panel-default">
   <div class="panel-body">

       <br>

    
       <div class="row">
           <div class="col-md-8">
               <div class="row">
                   <div class="col-md-3">
                       <%= @facility.user.name %>
                   </div>

                   <div class="col-md-9">
                       <h4><%= @facility.location_name %></h4>
                   

                       <div class="row text-center">
                           <div class="col-sm-3">
                               <i class="fa fa-home fa-2x"></i>
                           </div>
                           <div class="col-sm-3">
                               <i class="fa fa-usd fa-2x"></i>
                           </div>
                           <div class="col-sm-3">
                               <i class="fa fa-street-view fa-2x"></i>
                           </div>
                           <div class="col-sm-3">
                               <i class="fa fa-map fa-2x"></i>
                           </div>
                       </div>

                       <div class="row text-left">
                           <div class="col-sm-3">

                               <%= @facility.location_name %>
                           </div>
           
                           <div class="col-sm-3">
                               <h4>Price per hour</h4>
                               <%= @facility.price_per_hour %>
                           </div>

                           <div class="col-sm-3">
                               <h4>Street</h4>
                               <%= @facility.street %>
                           </div>

                           <div class="col-sm-3">
                               <h4>City</h4>
                               <%= @facility.city %>
                           </div><br>

                           <div class="col-sm-3">
                               <h4>Sport</h4>
                               <%= @facility.sport %>
                           </div>

                           <div class="col-sm-3">
                               <h4>Description</h4>
                               <%= @facility.description %>
                           </div>

                           <div class="col-sm-3">
                               <h4>Ratings</h4>
                               <%= @facility.ratings %>
                           </div><br><br>


                           <%= image_tag (@facility.avatars[0].thumb.url) if @facility.avatars[0] != nil %><br><br>

                           <%= link_to "Back to all Listings", user_facilities_path(current_user.id), class: "btn btn-primary" %>
                           <% if @facility.user_id == current_user.id %>
                               <%= link_to "Edit", edit_user_facility_path, class: "btn btn-primary" %>

                               <%= link_to "Delete", { controller: 'facilities', action: 'destroy' }, data: {confirm: 'Are you sure?'}, method: :delete, class: "btn btn-danger" %>
                           <% end %>
                       </div>
                   </div>
               </div>
           </div>
       </div>    
   </div>
</div>