config/routes.rb
Rails.application.routes.draw do
 
 resources :passwords, controller: "clearance/passwords", only: [:create, :new]
 resource :session, controller: "clearance/sessions", only: [:create]
 resources :users, controller: "clearance/users", only: [:create] do
   resource :password,
     controller: "clearance/passwords",
     only: [:create, :edit, :update]
 end

 root 'welcome#index'

  get '/search', to: 'facilities#search', as: "search"
  get '/search_bookings', to: 'bookings#search_bookings', as: "search_bookings"

resources :users do
  resources :facilities 
end

resources :bookings, only: [:update]

 resources :facilities do
    resources :bookings, only: [:index, :new, :show, :create] do
      resources :payments, only: [:new, :create]
    end
  end

 resources :users, controller: "users", only: :show
 get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, only: [:show, :edit, :update] do 
    resources :teams, only: [:new, :create, :edit, :update, :show, :destroy] 
  end

  get "/teams/:team_id/user_teams/new" => 'user_teams#new'
  post "/teams/:team_id/user_teams" => 'user_teams#create', as: "add_team_members"
  delete "/team/:team_id/user_teams/:id", to: 'user_teams#destroy', as: "delete_team_member"

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :photos

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base

  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    create! do |auth|
      auth.provider = auth_hash["provider"]
      auth.uid = auth_hash["uid"]
      auth.token = auth_hash["credentials"]["token"]
    end
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  has_many :payments
  belongs_to :facility
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :facility, presence: true

  searchkick match: :word_start, searchable: [:title, :notes, :facility_location_name]
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
	belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, scope: :recipient_id

	scope :involving, -> (user) do
		where("conversations.sender_id = ? OR conversations.recipient_id = ?", user.id, user.id)

	# equivalent to above
	# def self.involving(user)
	# 	where("conversations.sender_id = ? OR conversations.recipient_id = ?", user.id, user.id)
	# end

	#in controller model
	# Conversation.involving(current_user)
	
	scope :between, -> (sender_id, recipient_id) do
		where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", 
					sender_id, recipient_id, recipient_id, sender_id)
	end
end

app/models/facility.rb
class Facility < ActiveRecord::Base
	has_many :bookings
	validates :user_id, presence: true
	belongs_to :user

	# geocoded_by :address
	# after_validation :geocode, if: :address_changed?

	# validates :start_date, presence: true
	# validates :end_date, presence: true
	# validates :private, presence: true
	# validates :title, presence: true
	# validates :notes, presence: true
	# validates :total, presence: true
	validates :sport, presence: true
	mount_uploaders :avatars, AvatarUploader
	searchkick match: :word_start, searchable: [:street, :city, :state, :start_time, :end_time, :description, :location_name, :ratings, :price_per_hour, :sport]
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id

  def message_time
  	create_at.strftime("%v")
  end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :booking
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :user
  has_many :user_teams
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploaders :avatars, AvatarUploader
  include Clearance::User

  validates :email, uniqueness: true
  has_many :authentications, :dependent => :destroy
  has_many :facilities
  has_many :bookings
  has_many :user_teams
  has_many :teams

  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      #u.first_name = auth_hash["info"]["first_name"]
      # u.last_name = auth_hash["info"]["last_name"]
      # u.friendly_name = auth_hash["info"]["name"]
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.password = SecureRandom.hex(6)
      u.authentications<<(authentication)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end


  # def password_optional?
  #   true
  # end

end

app/models/user_team.rb
class UserTeam < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def edit
		@photos = @facility.photos
	end


	def destroy
		@photo = Photo.find(params[:id])
		facility = @photo.facility

		@photo.destroy
		@photos = Photo.where(facility_id: facility.id)

		respond_to :js
	end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show]
  def new
    @team = current_user.teams.new
  end

  def create
    @team = current_user.teams.new(team_params)
    if @team.save
      redirect_to user_team_path(current_user.id, @team.id)
    else
      render :new
    end
  end

  private
  def team_params
    params.require(:team).permit(:name, :location, :description)
  end

  def set_team
    @team = Team.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update]

  def update
  	if @user.update_attributes(user_params)
  		redirect_to user_path
  	else
  		render :edit
  	end
  end

  private
	def user_params	
		params.require(:user).permit(:email, :password, :name, :gender, :description, :contact_detail, :location_description, {avatars:[]})
	end

  def set_user
  	@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/user_teams_helper.rb
module UserTeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav id="header" class="navbar navbar-fixed-top" style="margin-left:100px; margin-top:20px;">
  <div id="header-container" class="container navbar-container">
    <ul class="nav nav-pills" >
      <li>
        <%= link_to root_path, class: "no-padding" do %>
        <div id="home-logo"></div>
        <% end %>
      </li>
      <% if signed_in? %>
       <li role="presentation" class="active"> 
        <%= form_for Booking.new, method: :get, url: search_bookings_path, class: "navbar-form navbar-left" do |f| %>
          <%= text_field_tag :term, params[:term], placeholder:"search for friendly match", style:"width:230px; margin-top:5px;" %>
          <%= f.submit 'search', class: 'btn btn-primary' %>
        <% end %>
      </li>

       <li role="presentation"><%= link_to t(".create_facility"), new_user_facility_path(current_user.id) %></li>
       <li role="presentation"><%= link_to "#{current_user.email}", user_path(current_user.id) %></li>
       <li role="presentation"><%= link_to t(".sign_out"), sign_out_path, method: :delete %></li>

       <li role="presentation">
         <%= form_for Facility.new, method: :get, url: search_path, class: "navbar-form navbar-left" do |f| %>
           <%= text_field_tag :term, params[:term], placeholder:"search for facilities", style:"width:230px; margin-top:5px;" %>
           <%= f.submit 'search', class: 'btn btn-primary' %>
         <% end %>
       </li>

     <% else %>
       
       <li role="presentation"><%= link_to t(".sign_up"), sign_up_path %></li>
       <li role="presentation"><%= link_to t(".sign_in"), sign_in_path %></li>
       <li role="presentation"><%= link_to "Connect With Facebook", "/auth/facebook" %></li>
     <% end %>
    </ul>
  </div><!-- /.container -->
</nav><!-- /.navbar -->

<div id="flash">
 <% flash.each do |key, value| %>
   <div id="flash_<%= key %>"><%=h value %></div>
 <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <title>BellyFIT</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
       <!-- Latest compiled and minified CSS -->
       <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

       <!-- jQuery library -->
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

       <script src="https://js.braintreegateway.com/v2/braintree.js"></script>

       <!-- Latest compiled JavaScript -->
       <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
       <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
       <%= csrf_meta_tags %>



  </head>

  <body>
        

          <%= render partial: "layouts/navbar" %>
          
          <div class="container content">
            <%= yield %>
          </div>
      
         
  </body>

</html>